import { Experience } from "@/types/content";

export const experiences: Experience[] = [
  {
    id: "icu-mortality-research",
    title: "ICU Mortality Risk Prediction Machine Learning Researcher",
    company: "National University of Singapore",
    program: "Supervisor: Dr. Kabir",
    location: "Singapore",
    dates: "August 2026 – Present",
    current: true,
    overview:
      "Researching multimodal methods for predicting mortality risk in ICU patients with cardiac dysrhythmias.",
    stack: ["PyTorch", "ResNet-50", "Neural ODEs", "ECG", "Medical Imaging"],
    bullets: [
      "Designing a **multimodal ICU mortality prediction model** that fuses a ResNet-50 chest X-ray encoder, a 1D ResNet ECG encoder, and a Neural ODE-based encoder for irregular longitudinal lab data.",
    ],
  },
  {
    id: "nia",
    title: "AI/Software Engineer Intern",
    company: "NiaHealth",
    program: "Health Tech · Series A",
    location: "Toronto, ON",
    dates: "August 2025 – July 2026",
    overview:
      "NiaHealth is a digital health startup building AI-powered tools for chronic disease management and clinician workflows.",
    stack: ["Agno", "FastAPI", "React", "TypeScript", "Python", "Postgres", "Azure", "Docker"],
    bullets: [
      "Improved food-photo macro extraction accuracy by **27%** over the baseline GPT vision model by integrating FNDDS nutrition retrieval into an Agno multi-agent pipeline and evaluating it on Google Nutrition5k.",
      "Built and deployed an asynchronous GPT integration and external-document pipeline on Azure, reducing medical-report parsing latency by **70%** (**10 to 3 minutes**) and saving the COO **9 hours/week** of manual review.",
      "Developed an AI-agent safety layer in Agno to validate patient reports against clinical recommendations, catching **8 report errors** before delivery and reducing legal-risk exposure.",
      "Owned end-to-end delivery of a React and Python cycle-tracking application for **8,000+ users**, partnering with clinical stakeholders from requirements through iterative UI and technical design.",
    ],
    photos: [
      {
        src: "/media-v1/toronto2.webp",
        alt: "Rithani presenting her work at NiaHealth",
        caption: "Presenting at NiaHealth",
        width: 1600,
        height: 1200,
      },
      {
        src: "/media-v1/toronto3.webp",
        alt: "Rithani with the NiaHealth team",
        caption: "The NiaHealth team",
        width: 1600,
        height: 1200,
      },
      { src: "/media-v1/toronto.webp", alt: "Rithani in Toronto", caption: "Toronto, Ontario", width: 1600, height: 2134 },
      {
        src: "/media-v1/experience/niahealth/noc-toronto-skyline.webp",
        alt: "Rithani with the NOC Toronto community overlooking the city skyline at sunset",
        caption: "Sunset with the NOC Toronto community",
        width: 1280,
        height: 960,
      },
      {
        src: "/media-v1/experience/niahealth/noc-toronto-friends.webp",
        alt: "Rithani exploring Toronto with friends from the NOC community",
        caption: "Exploring Toronto with friends",
        width: 1920,
        height: 1440,
      },
      {
        src: "/media-v1/experience/niahealth/team-rock-climbing.jpg",
        alt: "Rithani rock climbing with friends from the NiaHealth team",
        caption: "Rock climbing with the team",
        width: 1920,
        height: 1440,
      },
      {
        src: "/media-v1/experience/niahealth/niagara-falls.webp",
        alt: "Rithani and friends visiting Niagara Falls",
        caption: "Niagara Falls with NOC Toronto",
        width: 1920,
        height: 1440,
      },
      {
        src: "/media-v1/experience/niahealth/noc-celebration.webp",
        alt: "Rithani celebrating with friends from the NOC Toronto community",
        caption: "Celebrating with NOC Toronto",
        width: 1280,
        height: 960,
      },
      {
        src: "/media-v1/experience/niahealth/noc-friends-night.webp",
        alt: "Rithani gathered with friends during her NOC year in Toronto",
        caption: "A night with NOC friends",
        width: 1280,
        height: 720,
      },
      {
        src: "/media-v1/experience/niahealth/niahealth-remote-team.webp",
        alt: "The NiaHealth team together on a remote video call",
        caption: "Connecting with the remote NiaHealth team",
        width: 1920,
        height: 994,
      },
      {
        src: "/media-v1/experience/niahealth/niahealth-winter-team.webp",
        alt: "Rithani with the NiaHealth team during winter",
        caption: "Winter with the NiaHealth team",
        width: 1920,
        height: 1440,
      },
      {
        src: "/media-v1/experience/niahealth/team-game-night.webp",
        alt: "The NiaHealth team playing games together",
        caption: "NiaHealth team game night",
        width: 1920,
        height: 1440,
      },
    ],
    cardPhotos: [
      { src: "/media-v1/toronto2.webp", alt: "Rithani presenting her work at NiaHealth", caption: "Presenting at NiaHealth" },
      { src: "/media-v1/toronto3.webp", alt: "Rithani with the NiaHealth team", caption: "The NiaHealth team" },
    ],
    artifacts: [
      {
        title: "Final Internship Presentation",
        href: "/reports/niahealth/final-internship-presentation.pdf",
        type: "presentation",
        description: "A retrospective on the work, learning, and impact of the NiaHealth internship.",
        preview: {
          basePath: "/slides/niahealth/internship",
          pageCount: 15,
          filePrefix: "slide",
          aspect: "landscape",
        },
      },
      {
        title: "TR3203 Final Business Presentation",
        href: "/reports/niahealth/tr3203-final-business-presentation.pdf",
        type: "presentation",
        description: "Final business presentation developed around the NiaHealth experience.",
        preview: {
          basePath: "/slides/niahealth/business",
          pageCount: 31,
          filePrefix: "slide",
          aspect: "landscape",
        },
      },
      {
        title: "TR3203 Teaching Case",
        href: "/reports/niahealth/tr3203-teaching-case.pdf",
        type: "report",
        description: "Teaching case examining the NiaHealth business experience.",
        preview: {
          basePath: "/previews/niahealth/teaching-case",
          pageCount: 17,
          filePrefix: "page",
          aspect: "portrait",
        },
      },
      {
        title: "TR3203 Teaching Note",
        href: "/reports/niahealth/tr3203-teaching-note.pdf",
        type: "report",
        description: "Companion teaching note for the NiaHealth case.",
        preview: {
          basePath: "/previews/niahealth/teaching-note",
          pageCount: 14,
          filePrefix: "page",
          aspect: "portrait",
        },
      },
    ],
  },
  {
    id: "nus-ta",
    title: "Teaching Assistant — IS1108",
    company: "National University of Singapore",
    location: "Singapore",
    dates: "August 2024 – Present",
    current: true,
    overview:
      "IS1108 examines data ethics, digital privacy, and the real-world consequences of technology.",
    stack: ["Data Ethics", "Digital Privacy", "Critical Thinking", "Teaching"],
    bullets: [
      "Facilitated weekly tutorial sessions for **100+ students** on data ethics, digital privacy, and responsible technology use.",
      "Mentored students through real-world ethical dilemmas involving data collection, surveillance, and internal biases.",
    ],
    photos: [
      {
        src: "/media-v1/ta.webp",
        alt: "Rithani with her IS1108 students",
        caption: "IS1108 teaching assistant",
        width: 1600,
        height: 1200,
      },
      {
        src: "/media-v1/experience/ta/tutorial-team-selfie.webp",
        alt: "IS1108 students taking a group selfie after a tutorial activity",
        caption: "IS1108 tutorial team",
        width: 960,
        height: 1280,
      },
      {
        src: "/media-v1/experience/ta/tutorial-group-presentation.webp",
        alt: "IS1108 students presenting an AI governance framework",
        caption: "AI governance group presentation",
        width: 960,
        height: 1280,
      },
      {
        src: "/media-v1/experience/ta/ai-governance-group.webp",
        alt: "IS1108 student group with their AI governance stakeholder map",
        caption: "Mapping AI governance stakeholders",
        width: 960,
        height: 1280,
      },
      {
        src: "/media-v1/experience/ta/ai-stakeholders-group.webp",
        alt: "IS1108 student group presenting AI risks and stakeholders",
        caption: "Exploring AI risks and accountability",
        width: 960,
        height: 1280,
      },
      {
        src: "/media-v1/experience/ta/governance-framework-group.webp",
        alt: "IS1108 students with their classroom AI governance framework",
        caption: "Building an AI governance framework",
        width: 1920,
        height: 2560,
      },
    ],
    cardPhotos: [
      { src: "/media-v1/ta.webp", alt: "Rithani with her IS1108 students", caption: "IS1108 teaching assistant" },
    ],
  },
  {
    id: "nes-entrepreneurial-education",
    title: "Head of Entrepreneurial Education",
    company: "NUS Entrepreneurship Society",
    program: "NES Startathon · AY 2024/25",
    location: "Singapore",
    dates: "August 2024 – May 2025",
    overview:
      "Led the society's flagship experiential entrepreneurship program, connecting NUS students with founders, investors, and hands-on venture building.",
    stack: ["Program Leadership", "Entrepreneurship", "Team Management", "Stakeholder Engagement"],
    bullets: [
      "Managed a team of **20 people** and coordinated with an NUS Business School professor to lead NES Startathon, a **2 MC (Module Credit)** NUS entrepreneurship program, hosting weekly **3-hour sessions** for **35 students per semester**.",
      "Organized and engaged **26 founders and entrepreneurs** as mentors and **5 prominent venture capitalists** as judges, giving students direct exposure to real-world fundraising, scaling, and early-stage decision-making.",
    ],
    photos: [
      {
        src: "/media-v1/experience/nes/startathon-class.webp",
        alt: "NES Startathon students and facilitators in a classroom",
        caption: "The NES Startathon cohort",
        width: 1280,
        height: 960,
      },
      {
        src: "/media-v1/experience/nes/startathon-guest.webp",
        alt: "NES Startathon guest speaker receiving a token of appreciation",
        caption: "Learning from experienced founders",
        width: 960,
        height: 1280,
      },
      {
        src: "/media-v1/experience/nes/startathon-class-selfie.webp",
        alt: "NES Startathon facilitator taking a selfie with the class",
        caption: "A Startathon class in session",
        width: 1280,
        height: 960,
      },
      {
        src: "/media-v1/experience/nes/founder-session.webp",
        alt: "An entrepreneur speaking to NES Startathon students",
        caption: "Founder-led classroom session",
        width: 960,
        height: 1280,
      },
      {
        src: "/media-v1/experience/nes/nes-team.webp",
        alt: "NUS Entrepreneurship Society team in formal attire",
        caption: "The NUS Entrepreneurship Society team",
        width: 960,
        height: 1280,
      },
      {
        src: "/media-v1/experience/nes/getgo-visit.webp",
        alt: "NES Startathon students visiting the GetGo office",
        caption: "Industry visit to GetGo",
        width: 1280,
        height: 960,
      },
      {
        src: "/media-v1/experience/nes/startathon-cohort.webp",
        alt: "NES Startathon cohort posing together in a classroom",
        caption: "Startathon cohort gathering",
        width: 1280,
        height: 960,
      },
      {
        src: "/media-v1/experience/nes/startathon-class-group.webp",
        alt: "NES Startathon students posing together after class",
        caption: "Building ventures together",
        width: 1280,
        height: 960,
      },
    ],
    cardPhotos: [
      {
        src: "/media-v1/experience/nes/startathon-class.webp",
        alt: "NES Startathon students and facilitators in a classroom",
        caption: "NES Startathon",
      },
      {
        src: "/media-v1/experience/nes/nes-team.webp",
        alt: "NUS Entrepreneurship Society team in formal attire",
        caption: "The NES team",
        objectPosition: "center 42%",
      },
    ],
  },
  {
    id: "buymed",
    title: "Software Engineer Intern",
    company: "Buymed",
    program: "B2B Pharma E-Commerce · Series B",
    location: "Ho Chi Minh City, Vietnam",
    dates: "May 2024 – August 2024",
    overview:
      "Buymed connects pharmacies with drug manufacturers through a B2B pharmaceutical e-commerce platform across Southeast Asia.",
    stack: ["Go", "React", "Next.js", "MongoDB", "Python", "OpenAI API", "LangChain", "Pinecone"],
    bullets: [
      "Implemented REST API endpoints in Go for a concurrent pipeline that automated nightly pricing collection across **6 pharmaceutical sources**, plus a React dashboard used by a **35-person internal team**.",
      "Reduced website information retrieval time from **5 minutes to 10 seconds** by building a user-facing RAG chatbot with Pinecone, LangChain, and the OpenAI API.",
      "Collaborated with global engineering teams to deliver **10+ production features** and **15+ bug fixes** across the Thailand and Cambodia Next.js websites.",
    ],
    photos: [
      { src: "/media-v1/vietnam.webp", alt: "Rithani in Vietnam", caption: "Ho Chi Minh City, Vietnam", width: 1600, height: 2134 },
      {
        src: "/media-v1/experience/buymed/buymed-team-selfie.jpg",
        alt: "Rithani taking a selfie with Buymed teammates in the office",
        caption: "With the Buymed team",
        width: 1920,
        height: 1440,
      },
      {
        src: "/media-v1/experience/buymed/buymed-colleague-selfie.jpg",
        alt: "Rithani taking a selfie with two Buymed colleagues",
        caption: "A day at the Buymed office",
        width: 1920,
        height: 1440,
      },
      {
        src: "/media-v1/experience/buymed/buymed-office.jpg",
        alt: "Buymed office interior in Ho Chi Minh City",
        caption: "The Buymed office",
        width: 1440,
        height: 1920,
      },
      {
        src: "/media-v1/experience/buymed/community-event.jpg",
        alt: "A community gathering in Ho Chi Minh City",
        caption: "Community in Ho Chi Minh City",
        width: 1280,
        height: 853,
      },
      {
        src: "/media-v1/experience/buymed/noc-community.jpg",
        alt: "Rithani with the NOC Vietnam community",
        caption: "The NOC Vietnam community",
        width: 1280,
        height: 960,
      },
      {
        src: "/media-v1/experience/buymed/vietnam-friends.jpg",
        alt: "Rithani and friends gathered by the coast in Vietnam",
        caption: "Exploring Vietnam with friends",
        width: 1280,
        height: 960,
      },
    ],
    cardPhotos: [
      { src: "/media-v1/vietnam.webp", alt: "Rithani at the Buymed office", caption: "Buymed, Ho Chi Minh City", objectPosition: "center 30%" },
      { src: "/media-v1/vietnam3.webp", alt: "Rithani having dinner with friends in Vietnam", caption: "Life in Ho Chi Minh City" },
    ],
    artifacts: [
      {
        title: "ETP3205 Final Presentation",
        href: "/reports/buymed/etp3205-final-presentation.pdf",
        type: "presentation",
        description: "Final presentation reflecting on the Buymed internship experience in Vietnam.",
        preview: {
          basePath: "/slides/buymed/etp3205",
          pageCount: 15,
          filePrefix: "slide",
          aspect: "landscape",
        },
      },
      {
        title: "ETP3205 Internship Report",
        href: "/reports/buymed/etp3205-report.pdf",
        type: "report",
        description: "Internship report reflecting on the Buymed experience and NOC Vietnam.",
        preview: {
          basePath: "/previews/buymed/etp3205-report",
          pageCount: 11,
          filePrefix: "page",
          aspect: "portrait",
        },
      },
    ],
  },
];
