import { Passions } from "@/types/content";

export const passions: Passions = {
  Cooking: [
    { title: "Weeknight miso cod", note: "Sheet-pan, 20 min", image: "/passions/cooking/cooking-1.png" },
    { title: "Sourdough, batch 14", note: "Finally got the ear", image: "/passions/cooking/cooking-2.png" },
    { title: "Thosai + 3 chutneys", note: "Sunday ritual", image: "/passions/cooking/cooking-3.png" },
    { title: "Pho from scratch", note: "Bones, 8 hrs", image: "/passions/cooking/cooking-4.png" },
    { title: "Laminated croissants", note: "Butter wins", image: "/passions/cooking/cooking-5.png" },
    { title: "Chili oil noodles", note: "House special", image: "/passions/cooking/cooking-6.png" },
    { title: "Morning spread", note: "Avocado toast + kiwi", image: "/passions/cooking/cooking-7.png" },
    { title: "Weekend bake", note: "From scratch", image: "/passions/cooking/cooking-8.png" },
    { title: "Comfort bowl", note: "Rainy day", image: "/passions/cooking/cooking-9.png" },
    { title: "Plating practice", note: "Getting there", image: "/passions/cooking/cooking-10.png" },
    { title: "Fusion experiment", note: "East meets West", image: "/passions/cooking/cooking-11.png" },
    { title: "Holiday special", note: "Family recipe", image: "/passions/cooking/cooking-12.png" },
    { title: "Quick lunch", note: "15 min max", image: "/passions/cooking/cooking-13.png" },
    { title: "Date night", note: "Two courses", image: "/passions/cooking/cooking-14.png" },
    { title: "Farmers market haul", note: "Fresh & local", image: "/passions/cooking/cooking-15.png" },
    { title: "Breakfast spread", note: "Lazy Sunday", image: "/passions/cooking/cooking-16.png" },
    { title: "Spice rack session", note: "New blend", image: "/passions/cooking/cooking-17.png" },
    { title: "Meal prep", note: "Week ahead", image: "/passions/cooking/cooking-18.png" },
    { title: "Sweet tooth", note: "Dessert time", image: "/passions/cooking/cooking-19.png" },
    { title: "Kitchen chaos", note: "Worth it", image: "/passions/cooking/cooking-20.png" },
    { title: "Final plate", note: "Nailed it", image: "/passions/cooking/cooking-21.png" },
  ],
  Photography: [
    { title: "Toronto, 6am", note: "Kodak Gold", image: "/passions/photography/photography-1.png" },
    { title: "Hoi An lanterns", note: "Fuji X-T30", image: "/passions/photography/photography-2.png" },
    { title: "Kerala backwaters", note: "Portra 400", image: "/passions/photography/photography-3.png" },
    { title: "NUS arts quad", note: "35mm", image: "/passions/photography/photography-4.png" },
    { title: "Banff, October", note: "Cold, clean light", image: "/passions/photography/photography-5.png" },
    { title: "HCMC alleyways", note: "Ricoh GR", image: "/passions/photography/photography-6.png" },
    { title: "Golden hour", note: "Chasing light", image: "/passions/photography/photography-7.png" },
    { title: "Street scene", note: "Candid moment", image: "/passions/photography/photography-8.png" },
    { title: "Architecture", note: "Lines & shapes", image: "/passions/photography/photography-9.png" },
    { title: "Portrait", note: "Natural light", image: "/passions/photography/photography-10.png" },
    { title: "Cityscape", note: "After dark", image: "/passions/photography/photography-11.png" },
    { title: "Nature walk", note: "Morning dew", image: "/passions/photography/photography-12.png" },
    { title: "Travel diary", note: "New city", image: "/passions/photography/photography-13.png" },
    { title: "Reflections", note: "Still water", image: "/passions/photography/photography-14.png" },
    { title: "Market day", note: "Colours everywhere", image: "/passions/photography/photography-15.png" },
    { title: "Sunset chase", note: "Worth the wait", image: "/passions/photography/photography-16.png" },
    { title: "Old town", note: "Heritage walk", image: "/passions/photography/photography-17.png" },
    { title: "Film roll", note: "Analog days", image: "/passions/photography/photography-18.png" },
    { title: "Rooftop view", note: "City lights", image: "/passions/photography/photography-19.png" },
    { title: "Morning ritual", note: "Coffee & camera", image: "/passions/photography/photography-20.png" },
    { title: "Long exposure", note: "Smooth water", image: "/passions/photography/photography-21.png" },
    { title: "Texture study", note: "Close-up", image: "/passions/photography/photography-22.png" },
    { title: "Silhouettes", note: "Backlit", image: "/passions/photography/photography-23.png" },
    { title: "Final frame", note: "End of roll", image: "/passions/photography/photography-24.png" },
  ],
  Dancing: [
    { title: "Bharatanatyam", note: "Since age 6", image: "/passions/dancing/dancing-1.png" },
    { title: "Arangetram", note: "2022 · Chennai", image: "/passions/dancing/dancing-2.png" },
    { title: "Campus showcase", note: "NUS · 2024", image: "/passions/dancing/dancing-3.png" },
    { title: "Contemporary class", note: "Weekly", image: "/passions/dancing/dancing-4.png" },
    { title: "Student choreo", note: "Piece in 5", image: "/passions/dancing/dancing-5.png" },
    { title: "Festival stage", note: "Deepavali", image: "/passions/dancing/dancing-6.png" },
    { title: "Rehearsal", note: "Practice day", image: "/passions/dancing/dancing-7.png" },
    { title: "Performance", note: "Show night", image: "/passions/dancing/dancing-8.png" },
    { title: "Backstage", note: "Pre-show", image: "/passions/dancing/dancing-9.png" },
    { title: "Workshop", note: "New style", image: "/passions/dancing/dancing-10.png" },
    { title: "Group piece", note: "Team effort", image: "/passions/dancing/dancing-11.png" },
    { title: "Final bow", note: "Standing ovation", image: "/passions/dancing/dancing-12.png" },
  ],
};
