import { Passions } from "@/types/content";

export const passions: Passions = {
  Cooking: [
    { title: "Egg salad avocado toast", note: "Sheet-pan, 20 min", image: "/media-v1/passions/cooking/cooking-1.webp" },
    { title: "Cheese quesadilla, shrimp stir fry, roastedchickpeas", note: "Finally got the ear", image: "/media-v1/passions/cooking/cooking-2.webp" },
    { title: "Salmon + veggie stir fry, avocado, rice", note: "Sunday ritual", image: "/media-v1/passions/cooking/cooking-3.webp" },
    { title: "Poached eggs avocado toast + chilli oil", note: "Bones, 8 hrs", image: "/media-v1/passions/cooking/cooking-4.webp" },
    { title: "Salmon pasta", note: "Butter wins", image: "/media-v1/passions/cooking/cooking-5.webp" },
    { title: "Bagel done sweet and savory", note: "House special", image: "/media-v1/passions/cooking/cooking-6.webp" },
    { title: "Crispy fried salmon with ceasar salad", note: "Avocado toast + kiwi", image: "/media-v1/passions/cooking/cooking-7.webp" },
    { title: "Pesto Pasta", note: "From scratch", image: "/media-v1/passions/cooking/cooking-8.webp" },
    { title: "French toast, greek yogurt bowl", note: "Rainy day", image: "/media-v1/passions/cooking/cooking-9.webp" },
    { title: "Crispy tofu and veggie baguette", note: "Getting there", image: "/media-v1/passions/cooking/cooking-10.webp" },
    { title: "Tofu thai red curry", note: "East meets West", image: "/media-v1/passions/cooking/cooking-11.webp" },
    { title: "Honey garlic chicken and rice", note: "Family recipe", image: "/media-v1/passions/cooking/cooking-12.webp" },
    { title: "Tofu pad thai", note: "15 min max", image: "/media-v1/passions/cooking/cooking-13.webp" },
    { title: "Chicken and enoki mushroom stir fry, veggie salad, rice", note: "Two courses", image: "/media-v1/passions/cooking/cooking-14.webp" },
    { title: "Crispy fried tofu sandwich", note: "Fresh & local", image: "/media-v1/passions/cooking/cooking-15.webp" },
    { title: "Honey garlic salmon and enoki mushrooms", note: "Lazy Sunday", image: "/media-v1/passions/cooking/cooking-16.webp" },
    { title: "Veggie fresh rolls with peanut sauce", note: "New blend", image: "/media-v1/passions/cooking/cooking-17.webp" },
    { title: "Eggs, toast, strawberries", note: "Week ahead", image: "/media-v1/passions/cooking/cooking-18.webp" },
    { title: "Shrimp pad thai", note: "Dessert time", image: "/media-v1/passions/cooking/cooking-19.webp" },
    { title: "Tofu stir fry", note: "Worth it", image: "/media-v1/passions/cooking/cooking-20.webp" },
  ],
  Photography: [
    { title: "University Town, NUS", note: "Kodak Gold", image: "/media-v1/passions/photography/photography-1.webp" },
    { title: "Seattle downtown, Seattle", note: "Fuji X-T30", image: "/media-v1/passions/photography/photography-2.webp" },
    { title: "Seattle Great Wheel, Seattle", note: "Portra 400", image: "/media-v1/passions/photography/photography-3.webp" },
    { title: "Montreal, Canada", note: "35mm", image: "/media-v1/passions/photography/photography-4.webp" },
    { title: "Pike Place Market, Seattle", note: "Cold, clean light", image: "/media-v1/passions/photography/photography-5.webp" },
    { title: "University Town, NUS", note: "Ricoh GR", image: "/media-v1/passions/photography/photography-6.webp" },
    { title: "Golden hour", note: "Chasing light", image: "/media-v1/passions/photography/photography-7.webp" },
    { title: "Street scene", note: "Candid moment", image: "/media-v1/passions/photography/photography-8.webp" },
    { title: "Architecture", note: "Lines & shapes", image: "/media-v1/passions/photography/photography-9.webp" },
    { title: "Portrait", note: "Natural light", image: "/media-v1/passions/photography/photography-10.webp" },
    { title: "Cityscape", note: "After dark", image: "/media-v1/passions/photography/photography-11.webp" },
    { title: "Nature walk", note: "Morning dew", image: "/media-v1/passions/photography/photography-12.webp" },
    { title: "Travel diary", note: "New city", image: "/media-v1/passions/photography/photography-13.webp" },
    { title: "Reflections", note: "Still water", image: "/media-v1/passions/photography/photography-14.webp" },
    { title: "Market day", note: "Colours everywhere", image: "/media-v1/passions/photography/photography-15.webp" },
    { title: "Sunset chase", note: "Worth the wait", image: "/media-v1/passions/photography/photography-16.webp" },
    { title: "Old town", note: "Heritage walk", image: "/media-v1/passions/photography/photography-17.webp" },
    { title: "Film roll", note: "Analog days", image: "/media-v1/passions/photography/photography-18.webp" },
    { title: "Rooftop view", note: "City lights", image: "/media-v1/passions/photography/photography-19.webp" },
    { title: "Morning ritual", note: "Coffee & camera", image: "/media-v1/passions/photography/photography-20.webp" },
    { title: "Long exposure", note: "Smooth water", image: "/media-v1/passions/photography/photography-21.webp" },
    { title: "Texture study", note: "Close-up", image: "/media-v1/passions/photography/photography-22.webp" },
    { title: "Silhouettes", note: "Backlit", image: "/media-v1/passions/photography/photography-23.webp" },
    { title: "Final frame", note: "End of roll", image: "/media-v1/passions/photography/photography-24.webp" },
  ],
  Dancing: [
    { title: "Bharatanatyam", note: "Since age 6", image: "/media-v1/passions/dancing/dancing-1.webp" },
    { title: "Arangetram", note: "2022 · Chennai", image: "/media-v1/passions/dancing/dancing-2.webp" },
    { title: "Campus showcase", note: "NUS · 2024", image: "/media-v1/passions/dancing/dancing-3.webp" },
    { title: "Contemporary class", note: "Weekly", image: "/media-v1/passions/dancing/dancing-4.webp" },
    { title: "Student choreo", note: "Piece in 5", image: "/media-v1/passions/dancing/dancing-5.webp" },
    { title: "Festival stage", note: "Deepavali", image: "/media-v1/passions/dancing/dancing-6.webp" },
    { title: "Rehearsal", note: "Practice day", image: "/media-v1/passions/dancing/dancing-7.webp" },
    { title: "Performance", note: "Show night", image: "/media-v1/passions/dancing/dancing-8.webp" },
    { title: "Backstage", note: "Pre-show", image: "/media-v1/passions/dancing/dancing-9.webp" },
    { title: "Workshop", note: "New style", image: "/media-v1/passions/dancing/dancing-10.webp" },
    { title: "Group piece", note: "Team effort", image: "/media-v1/passions/dancing/dancing-11.webp" },
    { title: "Final bow", note: "Standing ovation", image: "/media-v1/passions/dancing/dancing-12.webp" },
  ],
};
