import { Project } from "@/types/content";

export const projects: Project[] = [
  {
    id: "closet-ai",
    name: "Closet AI — AI Wardrobe Stylist",
    category: "Product/SWE",
    blurb: "A private digital closet that turns clothing photos into organized garments, weather-aware outfits, and virtual try-ons.",
    description: "Built a desktop-first AI wardrobe and personal styling app that turns clothing photos into a private digital closet. Users can review extracted garment cutouts, organize what they own, teach the stylist their taste, generate weather-aware outfits, and preview looks with virtual try-on.",
    stack: ["Next.js", "React", "Supabase", "OpenAI", "PostgreSQL"],
    bullets: [
      "Built multi-garment image extraction that turns a single closet photo into clean, reviewable wardrobe items.",
      "Designed a taste-aware stylist that recommends three weather-appropriate outfits using pieces the user already owns.",
    ],
    images: ["/media-v1/projects/closet-ai-stylist-screen.webp"],
    featured: true,
  },
  {
    id: "intent-ledger",
    name: "Intent Ledger Shopping Copilot",
    category: "Artificial Intelligence",
    blurb: "Hybrid product retrieval over 50,000 items that scored 8.2× the baseline with 96.5% Hit Rate@10.",
    description: "Built the search and intent layer for a team shopping copilot at TikTok TechJam. The system tracks how requests evolve across a conversation, combines lexical and semantic retrieval, reranks results, and falls back gracefully when intent is ambiguous.",
    stack: ["Python", "SQLite FTS5", "Hybrid Retrieval", "Rank Fusion", "Evaluation"],
    bullets: [
      "Scored 8.2× the baseline, 96.5% Hit Rate@10, and 0.77 MRR over 50,000 products in a 200-session evaluation.",
      "Combined hybrid retrieval, ranking, multi-turn intent state, and fallbacks at 134 ms latency.",
    ],
    images: [],
    featured: true,
  },
  {
    id: "lock-in",
    name: "Lock In — Financial Accountability App",
    category: "Product/SWE",
    blurb: "Two MVPs that help students follow through by staking money on commitments and submitting proof for peer verification.",
    description: "Co-built a financial-accountability product for university students, owning the FastAPI backend, Next.js frontend, and Railway/Vercel deployment from prototype through user testing.",
    stack: ["FastAPI", "Next.js", "Supabase", "Railway", "Vercel"],
    bullets: [
      "Built two end-to-end MVPs and tested the accountability model with 45+ university students.",
      "Owned backend, frontend, data, and deployment across FastAPI, Next.js, Supabase, Railway, and Vercel.",
    ],
    images: ["/media-v1/LockIn.webp"],
    featured: true,
  },
  {
    id: "agent-observability",
    name: "Agent Observability Dashboard",
    category: "Artificial Intelligence",
    blurb: "Real-time tracing and evaluation for multi-agent tool calls, latency, token usage, failures, and regressions.",
    description: "Built an observability interface for understanding multi-agent systems as they run, pairing WebSocket traces with an evaluation harness that compares prompt and model versions.",
    stack: ["React", "TypeScript", "WebSockets", "LLM Evals"],
    bullets: [
      "Traced agent tool calls, latency, tokens, and failures in real time over WebSockets.",
      "Built an evaluation harness that tracks failure rates and catches regressions across prompt and model versions.",
    ],
    images: [],
  },
  {
    id: "sepsis",
    name: "Sepsis Mortality Prediction",
    category: "Machine Learning",
    blurb: "Mortality prediction and early detection of sepsis from time-series patient data using LSTM, based on MIMIC III.",
    description: "Built an end-to-end pipeline for early sepsis detection and mortality prediction using deep learning on electronic health records. Leveraged Google BigQuery to extract and transform over 40,000 patient records from the MIMIC III clinical database, then trained an LSTM network on time-series antibiotic administration data to predict patient outcomes.",
    stack: ["Google BigQuery", "MySQL", "Python", "R", "Keras", "Jupyter", "Pandas", "NumPy", "Matplotlib"],
    bullets: [
      "Analyzed over 40,000 rows of patient data from MIMIC III and identified a positive correlation between time to antibiotic after hospital admission and length of stay.",
      "Implemented a mortality prediction model by training an LSTM for early detection and prediction of sepsis based on time-series data of antibiotic administration.",
    ],
    images: ["/media-v1/images/projects/sepsis-1.webp"],
    videoSrc: "/NHouse Application Video.mp4",
    featured: true,
  },
  {
    id: "bioinks",
    name: "Bioinformatics Independent Research",
    category: "Machine Learning",
    blurb: "Machine learning approach to classify and select bio-inks based on chemical, physical, and biological properties for 3D-printed tissue quality.",
    description: "Conducted independent research applying machine learning to the field of bioprinting. Developed classification models to predict 3D-printed tissue quality based on bio-ink chemical, physical, and biological properties, enabling researchers to select optimal ink formulations before printing.",
    stack: ["Python", "Jupyter", "Scikit-learn", "Pandas", "NumPy", "Matplotlib"],
    bullets: [
      "Used Random Forests, Logistic Regression, XGBoost, and SVM to classify data as high vs low quality 3D-printed tissues, achieving 85% AUC-ROC.",
    ],
    images: ["/media-v1/images/projects/bioinks-1.webp"],
    videoSrc: "/PGPR Cluster Leader Application Video.mp4",
    featured: true,
  },
  {
    id: "mudra",
    name: "Bharatanatyam Mudra Practice Tool",
    category: "Product/SWE",
    blurb: "Live-camera practice tool with 88.7% accuracy across 28 mudras, tested with 20+ Bharatanatyam students over 8 weeks.",
    description: "Built a live-camera Bharatanatyam practice tool using Google MediaPipe to track 21 hand landmarks and classify all 28 single-hand mudras. Trained the model on 1,400+ custom samples, then evaluated how the tool changed independent practice over an eight-week test.",
    stack: ["Python", "Google MediaPipe", "Flask", "JavaScript", "HTML/CSS"],
    bullets: [
      "Improved independent practice by 22% for 20+ students during an eight-week test.",
      "Reached 88.7% accuracy across 28 mudras using 1,400+ custom training samples and MediaPipe hand landmarks.",
    ],
    images: ["/media-v1/projects/mudra-screen.webp"],
    live: "https://mudra-mediapipe.vercel.app",
  },
  {
    id: "rag",
    name: "Retrieval-Augmented Generation for Domain-Specific QA",
    category: "Artificial Intelligence",
    blurb: "Modular RAG framework for question answering over unstructured multi-format academic documents (PDF, DOCX, Markdown).",
    description: "Designed a modular Retrieval-Augmented Generation pipeline for domain-specific question answering over academic documents. The system ingests PDF, DOCX, and Markdown files, chunks them with sentence-aware strategies, generates dense embeddings, and retrieves relevant passages for LLM-grounded response synthesis.",
    stack: ["Python", "LlamaIndex", "Weaviate", "Ollama", "Mistral", "HuggingFace", "Streamlit"],
    bullets: [
      "Designed and implemented sentence-aware chunking and configurable overlap strategies; generated dense embeddings with LlamaIndex + HuggingFace and indexed in Dockerized Weaviate for Top-K semantic retrieval.",
      "Integrated a local LLM (Mistral via Ollama) for grounded response synthesis and analyzed retrieval relevance and source attribution.",
    ],
    images: ["/media-v1/images/projects/rag-1.webp"],
  },
  {
    id: "dropout",
    name: "ML Pipeline — Student Dropout Prediction",
    category: "Machine Learning",
    blurb: "End-to-end ML pipeline for student dropout prediction using engineered features and LightGBM.",
    description: "Built a complete ML pipeline from data ingestion through model evaluation for predicting student dropout risk. Engineered 67 features from raw academic records and trained a LightGBM classifier with MLflow experiment tracking for reproducibility.",
    stack: ["Python", "Pandas", "NumPy", "Scikit-learn", "LightGBM", "MLflow", "Matplotlib", "Seaborn"],
    bullets: [
      "Processed 382 student records across 67 engineered features; merged datasets, created interaction variables, and applied standardization for improved interpretability.",
      "Built and trained a LightGBM binary classifier achieving 80% AUC-ROC with early stopping and hyperparameter optimization; tracked experiments with MLflow.",
    ],
    images: ["/media-v1/images/projects/dropout-1.webp"],
  },
  {
    id: "aws-rek",
    name: "AWS Image Label",
    category: "Product/SWE",
    blurb: "AWS-based image storage and labelling using S3 and Rekognition.",
    description: "Cloud-native image classification service built on AWS. Configured IAM roles and S3 buckets for secure image storage, then integrated Amazon Rekognition for automated label detection and classification of uploaded images.",
    stack: ["AWS S3", "IAM", "Rekognition", "Python", "Jupyter", "GitHub"],
    bullets: [
      "Created an AWS IAM role and configured policy permissions for S3 and Rekognition.",
      "Leveraged Amazon Rekognition alongside S3 for efficient storage and labelling of image datasets.",
    ],
    images: ["/media-v1/images/projects/aws-rek-1.webp"],
  },
];
